version: '3.8'

services:
  # --- DATABASE ---
  postgres_db:
    image: postgres:15
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  # --- MONGODB ---
  mongo_db:
    image: mongo:6.0
    container_name: my_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123

  # --- SFTP SERVER ---
  sftp_server:
    image: atmoz/sftp
    container_name: my_sftp
    ports:
      - "2222:22"
    command: user:pass:1001
    volumes:
      - ./sftp_data:/home/user/upload

  # --- STORAGE (MINIO S3) ---
  minio:
    image: minio/minio
    container_name: my_minio
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console UI Port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/raw-data;
      /usr/bin/mc mb myminio/delta-lake;
      exit 0;
      "

  ingestion_app:
    build: .
    container_name: my_ingestion_app
    depends_on:
      - postgres_db
      - minio
      - createbuckets
    volumes:
      - ./configs:/app/configs
      - ./src:/app/src
    environment:
      - DB_PASSWORD=mysecretpassword
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - S3_ENDPOINT=http://minio:9000

volumes:
  pg_data:
  minio_data: